apiVersion: v1 
kind: Service 
metadata:
  name: boardgame-service
spec:
  type: NodePort
  selector:
    app: boardgame-cicd
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
